# Generated by Django 3.1.7 on 2021-02-27 23:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 23, 40, 17, 63235, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 23, 40, 17, 62232, tzinfo=utc)),
        ),
    ]
